[book]
authors = ["Alex"]
src = "src"
title = ""

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.html.fold]
enable = true

[output.html]
default-theme = "ayu"
preferred-dark-theme= "ayu"
no-section-label = true
git-repository-url = "https://github.com/jackdaw3/eve-starweb-wiki"